name: Sole Deployer
description: Deploys Kubernetes and Terraform updates
inputs:
  kubeconfig_data:
    description: Base64 encoded config for the target Kubernetes cluster
    required: true
  env_files:  # id of input
    description: Comma-seperated list of .env files to use during deployment
    required: true
  manifest_locations:  # id of input
    description: Comma-seperated list of directories containing Kubernetes manifest files to be applied to the target cluster
    required: true
  terraform_directory:  # id of input
    description: Directory containing Terraform files to be applied
    required: true
  terraform_workspace:  # id of input
    description: The Terraform workspace of the changes to be applied
    required: true
  terraform_var_file:  # id of input
    description: Location of the terraform var file
    required: true
runs:
  using: docker
  image: Dockerfile
